on:
  pull_request:
    types: [edited, synchronize, opened]
  push: 
    branches: [master, main]
  workflow_dispatch:
jobs:
    lint-and-check-formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: "Use node version"
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc
                  cache: 'npm'
            - name: "Install dependencies"
              run: npm install
            - name: "Linting with ESLint"
              run: npm run lint
            - name: Check formatting with Prettier
              run: npm run check-formatting 
    build:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          - name: "Use node version"
            uses: actions/setup-node@v4
            with:
                node-version-file: .nvmrc
                cache: 'npm'
          - name: "Install dependencies"
            run: npm install
          - name: "Build"
            run: npm run build
          - name: Archive production artifacts
            uses: actions/upload-artifact@v4
            with:
              name: dist-without-markdown
              path: |
                main.js
    run-tests:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          - name: "Use node version"
            uses: actions/setup-node@v4
            with:
                node-version-file: .nvmrc
                cache: 'npm'
          - name: "Install dependencies"
            run: npm install
          - name: Run tests
            run: npm run test
    run-typecheck:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          - name: "Use node version"
            uses: actions/setup-node@v4
            with:
                node-version-file: .nvmrc
                cache: 'npm'
          - name: "Install dependencies"
            run: npm install
          - name: Typechecking
            run: npm run typecheck
